-- Create Account Table
CREATE TABLE IF NOT EXISTS accounts (
    uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

GRANT ALL PRIVILEGES ON TABLE IF NOT EXISTS accounts TO ssq_user;
GRANT USAGE, SELECT ON SEQUENCE IF NOT EXISTS accounts_id_seq TO ssq_user;
